---
title: Demo
weight: 1
output: hugodown::md_document
---

## System setup

* `install.packages("devtools")`. [Setup chapter of the R packages book](https://r-pkgs.org/setup.html).

* usethis and devtools setup in my .Rprofile. `usethis::edit_r_profile()`

## Package creation

* `available::available("minipkg")`

* `usethis::create_package("/home/maelle/Documents/teaching/minipkg")`

* `usethis::use_git()`

* in a shell `git branch -m master main`

* `usethis::use_r("current-time")`

* `devtools::load()`, `what_time()`

* Insert roxygen2 skeleton.

* `devtools::document()`, `?what_time`

* `devtools::check()`, `usethis::use_mit_license` 

* add an argument, `@param language blabla` in docs, `devtools::document()`, `?what_time`

* `usethis::use_test("current-time")`

* `devtools::test()`

* `devtools::check()`

*  modify function, `use_package("praise")`

* `devtools::check()`

* `usethis::use_readme_rmd()`, write stuff

* `usethis::use_github()`,  `usethis::use_github_links()`

* `usethis::use_github_action_check_standard()`

* `install.packages("pkgdown")`, `usethis::use_pkgdown()`, `pkgdown::build_site()`

* `usethis::use_github_action("pkgdown")`, change GitHub pages settings of the repo, add URL to pkgdown config and to DESCRIPTION.